### ISSUE TITLE
Assemble katacoda tutorial for Stratis

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-docs#154]
We'll want to write the katacoda tutorial, and then link to it from our existing website.

**Comment by mulkieran** [comment]
There is a protocol, and it may make the most sense to develop directly against a RH repo, rather than against our docs repo.

**Comment by mulkieran** [comment]
I don't think it'll hurt to get started on this soon. @waltdisgrace : @drckeefe has prior experience with assembling katacoda tutorials, so if you run into any problems, he is the best person to ask.

**Comment by mulkieran** [comment]
Assigning to dkeefe for follow up.

**Comment by mulkieran** [comment]
@lleshchi, @drckeefe It looks like the tutorial uses a pre 2.0 version of Stratis. Is there any way that we can change that, to make it more up-to-date?

**Comment by drckeefe** [comment]
This might be due to the version of the virtual machine being used.  If the VM is older, such as, 8.1 then it will only have access to the repos that hold older versions of stratis-cli and stratisd.  I don't believe that we should try to clone and compile a new version for the users in the tutorial or try to upgrade the system.  If there is a file that defines which OS the tutorial should use, I'm not aware of it.   We could ask Scott if there is a way to update the OS version, but that might be a global change.

**Comment by mulkieran** [comment]
@lleshchi, @drckeefe Is this harder to do remotely?

**Comment by drckeefe** [comment]
No, being remote shouldn't add any additional work.

**Comment by lleshchi** [comment]
PR can be found here:
https://github.com/rhel-labs/learn-katacoda/pull/114

**Comment by mulkieran** [comment]
The linked issue looks merged. I think we should try to put it in our website.

**Comment by lleshchi** [comment]
It is not complete yet. I received some additional feedback, so I am currently revising. It has been merged in order to allow for testing, but is currently hidden from lab.redhat.com

**Comment by lleshchi** [comment]
Here is the new PR with revisions: https://github.com/rhel-labs/learn-katacoda/pull/116

**Comment by lleshchi** [comment]
Final revisions: https://github.com/rhel-labs/learn-katacoda/pull/118

**Comment by mulkieran** [comment]
@lleshchi Great! Once it's public we'll go ahead and link to it.

**Comment by mulkieran** [comment]
Closed by attached PRs.
