### ISSUE TITLE
Need to update design doc to indicate the UUIDs in variable length metadata are hyphenated

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-docs#40]
See: https://github.com/stratis-storage/stratisd/pull/382.

**Comment by agrover** [comment]
they aren't hyphenated.

**Comment by mulkieran** [comment]
I am convinced that they are in the variable length metadata as we use uuid's serialization and deserialization functionality: https://github.com/rust-lang-nursery/uuid/blob/master/src/serde.rs#L12.

**Comment by agrover** [comment]
How we use json is defined not by the serde default but by how we document it in the design doc. So we may need to revisit the code that relies on serde to define how to serialize uuids.

**Comment by mulkieran** [comment]
I doubt you will find many examples where UUIDs are serialized in JSON where they have any other format than the hyphenated one. This is probably why the uuid developers choose that as their one format. This is one area where we probably shouldn't break new ground. We would get to pay the price of doing extra development, while simultaneously defeating many users' expectations.

**Comment by agrover** [comment]
My point here is that this is something that was specified in the design doc, was implemented to match, and then the implementation changed to do something different. So now the design doc is wrong?

* We only noticed after the fact that stratisd is now emitting non-designdoc-conforming json
* uuid implementing `serde::Serializable` isn't apparent in the uuid 0.5.0 docs (as far as I can see [here](https://docs.rs/uuid/0.5.0/uuid/index.html)). So the format is also not documented. They could then change it later (to urn format, who knows?), thus causing stratisd to break again if we're just going with whatever uuid chose instead of specifying.

So I think we need to talk about this more, but later, after we reach 0.1 milestone, ok? Until then, let's just ignore this small inconsistency between the spec and impl.

**Comment by mulkieran** [comment]
* The commit message that made the change was quite explicit about the change. There was no _noticing_. I added this issue once the PR that contained the commit was merged. I did exactly the same for the previous design doc change.
* That uuid implements serde is stated explicitly in their docs (search for serde). Nothing will break for us even if they do change, because we will serialize and deserialize using a _presumably_ correct implementation, theirs.

We have already discussed that we may have to change the design doc, if necessary or desirable and we have already done so at least once. I believe that this is another instance where it makes sense and I said so in my original commit message where the change was made.

**Comment by agrover** [comment]
ok, sorry I missed that in the original commit message. I'm still not seeing Serialize mentioned in the uuid docs -- using the docs link I posted above I'm still not seeing anything when searching for serialize or serde. In looking at https://docs.rs/crate/uuid/0.5.0/source/src/serde.rs I see nothing that says they're committed to a particular string representation other than it's something that they can deserialize/parse (which I'm assuming is any of the formats they support.)

So just to summarize, I'm in agreement about serializing uuids to a hyphenated format, I just want to verify that it's documented and will not change later. Maybe we can do a little PR against uuid to add a docstring for `Uuid:serialize` to that effect to make it super easy for them to explicitly commit to this. Maybe I'm paranoid, I just would like this 100% nailed down. In the meantime I'll update the design doc.
